language: java
dist: trusty
sudo: false
jdk:
  - openjdk8
script: "mvn cobertura:cobertura"
before_install:
  - pip install --user codecov
after_success:
  - codecov
branches:
  except:
    - appveyor
